### ISSUE TITLE
All subset points are used to query its neighbours at training phase.

### ISSUE THREAD

**Issue by OuyangJunyuan** [yancie-yjr/DBQ-SSD#1]
1. How to obtain DYNAMIC_COST is presented in the configuration file.
2. Why all subset points are used to query instead of these active ones?

**Comment by yancie-yjr** [comment]
hello, (1) DYNAMIC_COST is the latency calculated before training, then it is distributed for each group of each stage corresponding to their parameter.
(2) The query operation is data-driven, we do not carry out any prior query manner.
